@url = "http://localhost:3000/"

GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/ HTTP/1.1

###
POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
    "title": "Flight to Canada",
    "time": "1pm",
    "price": 26000,
    "date": "26-06-2022"
}

###
PUT http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
    "title": "Flight to Nigeria",
    "time": "1pm",
    "price": 26000,
    "date": "26-06-2022"
}

###
DELETE http://localhost:3000/ HTTP/1.1